#!/bin/bash
# SessionStart hook: writes session_id → cwd-indexed lookup file and the
# initial task placeholder. Fires on startup, resume, clear, compact and fork.

export PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:${PATH:-}"

INPUT=$(cat)
SESSION_ID=$(echo "$INPUT" | jq -r '.session_id // empty' 2>/dev/null)
CWD=$(echo "$INPUT" | jq -r '.cwd // empty' 2>/dev/null)
SOURCE=$(echo "$INPUT" | jq -r '.source // "startup"' 2>/dev/null)

if [ -z "$SESSION_ID" ] || [ -z "$CWD" ]; then
  exit 0
fi

# Hash the cwd to a short 8-char key (macOS + Linux)
cwd_hash() {
  if command -v md5 &>/dev/null; then
    echo "$1" | md5 | cut -c1-8
  else
    echo "$1" | md5sum | cut -c1-8
  fi
}
CWD_HASH=$(cwd_hash "$CWD")
TASKS_DIR="$HOME/.claude/session-tasks"
mkdir -p "$TASKS_DIR"

# Write session_id to lookup file (overwrites previous session for this cwd)
echo "$SESSION_ID" > "$TASKS_DIR/current_${CWD_HASH}.txt"

# Write initial task file: show dir + git branch as placeholder.
# On resume/compact/clear the session already has a tracked task; keep it
# instead of resetting the statusline to the placeholder mid-task.
TASK_FILE="$TASKS_DIR/${SESSION_ID}.txt"
if [ ! -f "$TASK_FILE" ] || [ "$SOURCE" = "startup" ]; then
  DIR_NAME="${CWD##*/}"
  BRANCH=$(git -C "$CWD" rev-parse --abbrev-ref HEAD 2>/dev/null)
  if [ -n "$BRANCH" ]; then
    echo "INIT:${DIR_NAME}  [${BRANCH}]" > "$TASK_FILE"
  else
    echo "INIT:${DIR_NAME}" > "$TASK_FILE"
  fi
fi

# Clean up task files (and their lock/generation sidecars) older than 7 days
find "$TASKS_DIR" \( -name "*.txt" -o -name "*.txt.lock" -o -name "*.txt.gen" \) \
  ! -name "current_*.txt" -mtime +7 -delete 2>/dev/null

# --- Plugin install: keep a stable launcher for the statusline ---
# ${CLAUDE_PLUGIN_ROOT} changes with every plugin version, but the statusLine
# entry in settings.json has to be a fixed path. ${CLAUDE_PLUGIN_DATA} survives
# updates, so a tiny launcher there always points at the current version.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [ -n "${CLAUDE_PLUGIN_DATA:-}" ]; then
  mkdir -p "$CLAUDE_PLUGIN_DATA" 2>/dev/null
  LAUNCHER="$CLAUDE_PLUGIN_DATA/statusline.sh"
  printf '#!/bin/bash\n# Generated by claude-tab-tracking; points at the installed plugin version.\nexec "%s/session_statusline.sh" "$@"\n' "$SCRIPT_DIR" > "$LAUNCHER.tmp" \
    && mv "$LAUNCHER.tmp" "$LAUNCHER" && chmod +x "$LAUNCHER"
  # One-time hint until the statusline is wired up
  SETTINGS="${CLAUDE_CONFIG_DIR:-$HOME/.claude}/settings.json"
  if [ "$SOURCE" = "startup" ]; then
    CURRENT_SL=$(jq -r '.statusLine.command // ""' "$SETTINGS" 2>/dev/null)
    case "$CURRENT_SL" in
      "$LAUNCHER"*|*session_statusline*|*claude-tab-tracking*) ;;
      "") echo "[tab] Task tracking is active but not shown yet: run /tab:setup to add it to your statusline." ;;
      *)  echo "[tab] Task tracking is active. Your statusline is set to another tool; run /tab:setup to embed the task line as a segment." ;;
    esac
  fi
fi

MEMO_CONFIG="$HOME/.claude/memos/config.yaml"
config_off() {  # config_off KEY -> true when "KEY: false" is set in config.yaml
  [ -f "$MEMO_CONFIG" ] && grep -Eiq "^[[:space:]]*$1[[:space:]]*:[[:space:]]*(false|no|off|0)[[:space:]]*$" "$MEMO_CONFIG"
}

# --- Handoff replay: same directory, same git HEAD, within 7 days ---
HANDOFF="$TASKS_DIR/handoff_${CWD_HASH}.json"
if [ "$SOURCE" = "startup" ] && [ -f "$HANDOFF" ] && ! config_off handoff; then
  H_TASK=$(jq -r '.task // ""' "$HANDOFF" 2>/dev/null)
  H_HEAD=$(jq -r '.head // ""' "$HANDOFF" 2>/dev/null)
  H_AT=$(jq -r '.at // 0' "$HANDOFF" 2>/dev/null)
  NOW=$(date +%s)
  AGE=$(( NOW - ${H_AT:-0} ))
  CUR_HEAD=$(git -C "$CWD" rev-parse HEAD 2>/dev/null || echo "")
  if [ -n "$H_TASK" ] && [ "$AGE" -lt 604800 ] 2>/dev/null; then
    if [ "$H_HEAD" = "$CUR_HEAD" ]; then
      if [ "$AGE" -lt 3600 ]; then AGE_FMT="$(( AGE / 60 ))m"; elif [ "$AGE" -lt 86400 ]; then AGE_FMT="$(( AGE / 3600 ))h"; else AGE_FMT="$(( AGE / 86400 ))d"; fi
      echo "[tab] Last session in this directory (${AGE_FMT} ago, HEAD unchanged): ${H_TASK}"
      echo "[tab] Continue where it left off, or run /tab:recall to load that day's memos."
    fi
  fi
fi

# --- One-line pointer in Claude Code's own auto-memory index (never content) ---
# Auto-memory is keyed by the git root; outside git, by the directory itself.
if [ "$SOURCE" = "startup" ] && ! config_off memory_pointer; then
  ROOT=$(git -C "$CWD" rev-parse --show-toplevel 2>/dev/null || echo "$CWD")
  ENCODED=$(printf '%s' "$ROOT" | sed 's/[^A-Za-z0-9]/-/g')
  MEMORY_MD="${CLAUDE_CONFIG_DIR:-$HOME/.claude}/projects/${ENCODED}/memory/MEMORY.md"
  PROJECT_NAME=$(basename "$ROOT" | sed 's/[^A-Za-z0-9_-]/-/g' | tr '[:upper:]' '[:lower:]' | cut -c1-50)
  if [ -f "$MEMORY_MD" ] && [ -d "$HOME/.claude/memos/$PROJECT_NAME" ] \
     && ! grep -q 'Conversation memos (claude-tab-tracking)' "$MEMORY_MD" 2>/dev/null; then
    printf '%s\n' "- Conversation memos (claude-tab-tracking): per-day decisions/TODOs for this project are in ~/.claude/memos/${PROJECT_NAME}/; load with /tab:recall, browse with /tab:memo" >> "$MEMORY_MD"
  fi
fi

# --- Memo overview (only on a fresh start; stdout becomes session context) ---
MEMO_DIR="$HOME/.claude/memos"
if [ "$SOURCE" = "startup" ] && [ -d "$MEMO_DIR" ]; then
  OVERVIEW=""
  for proj_dir in "$MEMO_DIR"/*/; do
    [ -d "$proj_dir" ] || continue
    proj_name=$(basename "$proj_dir")
    [ "$proj_name" = "_archive" ] && continue

    latest=""
    while IFS= read -r memo_file; do
      [ -z "$memo_file" ] && continue
      fname=$(basename "$memo_file" .md)
      count=$(grep -c '^## ' "$memo_file" 2>/dev/null)
      count=${count:-0}
      if [ "$count" -gt 0 ] 2>/dev/null; then
        if [ -z "$latest" ]; then
          latest="$fname ${count}"
        else
          latest="$latest | $fname ${count}"
        fi
      fi
    done < <(ls -t "$proj_dir"*.md 2>/dev/null | head -2)

    if [ -n "$latest" ]; then
      OVERVIEW="$OVERVIEW  $proj_name  $latest
"
    fi
  done

  if [ -n "$OVERVIEW" ]; then
    echo "[memo] Recent projects:"
    printf '%s' "$OVERVIEW" | head -5
    echo "Type /tab:recall for details"
  fi
fi

exit 0
